UNET_ARGS:
  dim: 64
  num_classes: 10
  cond_drop_prob: 0.2
  channels: 3
DIFFUSER_ARGS:
  image_size: 32
  timesteps: 1000
  beta_schedule: 'cosine'
TRAINER_ARGS:
  dataset_name: 'CIFAR10'
  dataset_path: 'PyTorch-StudioGAN/data'
  num_classes: 10
  train_batch_size: 512
  train_num_steps: 100000
  train_lr: 0.00008
  augment_horizontal_flip: true
  gradient_accumulate_every: 1
  ema_update_every: 10
  ema_decay: 0.995
  save_and_sample_every: 2000
  num_samples: 100
  results_folder: './results_CIFAR10'
  amp: false
  fp16: false
  calculate_fid: true
  num_workers: 6