# This is probably gonna be a headache. Train last.
UNET_ARGS:
  dim: 64
  num_classes: 10
  dim_mults: !!python/tuple [1, 2, 4]
  cond_drop_prob: 0.2
  channels: 1
DIFFUSER_ARGS:
  image_size: 28
  timesteps: 1000
  beta_schedule: 'cosine'
TRAINER_ARGS:
  dataset_name: 'MNIST'
  dataset_path: '../PyTorch-StudioGAN/data'
  num_classes: 10
  train_batch_size: 512
  train_num_steps: 10000
  train_lr: 0.00008
  augment_horizontal_flip: false
  gradient_accumulate_every: 1
  ema_update_every: 10
  ema_decay: 0.995
  save_and_sample_every: 1000
  num_samples: 100
  results_folder: './results_MNIST'
  amp: false
  fp16: false
  calculate_fid: false # FID on MNIST is useless
  num_workers: 6
